### ISSUE TITLE
Salute & Query

### ISSUE THREAD

**Issue by lixus7** [aptx1231/Traffic-Prediction-Open-Code-Summary#1]
Hello, congratulate for your work in AAAI 2022, and could you offer the code of "STDEN: Towards Physics-guided Neural Networks for Traffic Flow Prediction" because i want to use the newest state-of-art work to be the baseline of the future work. I will appreciate it very much if it can be offered.

**Comment by aptx1231** [comment]
Sorry for the late reply, we are collating the code and will get back to you with the link after the open source. You can follow the first author of the paper [Echo-Ji](https://github.com/Echo-Ji) .

**Comment by aptx1231** [comment]
Code has been updated : https://github.com/Echo-Ji/STDEN
